# -*- coding: utf-8 -*-
"""C107 PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fm6vUSVG-gRFlRP9Ew5JUYMcfDU57wwQ
"""

import pandas as pd
import plotly.express as px
import csv
import numpy as np
from google.colab import files 
data_to_load = files.upload()

df = pd.read_csv("C107 Project Data.csv")
mean = df.groupby("level")["attempt"].mean()
print(mean)

fig = px.scatter(df, x=mean, y=['Level 1', 'Level 2', 'Level 3', 'Level 4'])
fig.show()